version: '3.9'

services:

  centos-dev:
    image: centos
    container_name: centos-dev
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]

  influxdb:
    image: influxdb
    container_name: influxdb
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]

  postgres:
    image: postgres
    container_name: postgres
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]

  services:
    image: centos
    container_name: services
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]

  ubuntu-dev:
    image: ubuntu
    container_name: ubuntu-dev
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]

  jupyterhub:
    image: jupyterhub/jupyterhub
    container_name: jupyterhub
    working_dir: /root
    tty: true
    extra_hosts:
      - "raw.githubusercontent.com:199.232.28.133"
    command: ["/bin/sh"]



